### ISSUE TITLE
flask-google-login: login_user fails to set sessions cookie

### ISSUE THREAD

**Issue by gsidhu** [realpython/materials#116]
I am using this code by splitting it into a separate blueprint and using the application factory method. I am able to get to the user's data from Google and it reflects the in the db as well, but the `login_user` function fails with the following error –

```python
Traceback (most recent call last):
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/user/otpd/venv/lib/python3.6/site-packages/flask/sessions.py", line 387, in save_session
    samesite=samesite,
  File "/home/user/otpd/venv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 481, in set_cookie
    samesite=samesite,
  File "/home/user/otpd/venv/lib/python3.6/site-packages/werkzeug/http.py", line 1163, in dump_cookie
    buf = [key + b"=" + _cookie_quote(value)]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'
```
I am unable to figure out what the reason could be. Any suggestions?

If it helps - I am deploying this code on a remote server using Gunicorn.

Thanks!

**Comment by gsidhu** [comment]
Fixed. I had set an invalid SESSION_COOKIE_NAME in my config file. Changed that and everything works.

For the adventurers who end up on this issue in the future: Make sure you are setting up session environment variables correctly! You need an app secret and a session cookie name for Flask Sessions to run.
